/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/sync/state': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** State */
    get: operations['state_api_v1_sync_state_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sync/batches': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload */
    post: operations['upload_api_v1_sync_batches_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CloudStreamCursor */
    CloudStreamCursor: {
      /**
       * Stream
       * @enum {string}
       */
      stream:
        | 'telemetry'
        | 'registry'
        | 'intelligence'
        | 'optimization'
        | 'dispatch'
        | 'finance'
        | 'ai';
      /** Acknowledged Sequence */
      acknowledged_sequence: number;
    };
    /** CloudSyncState */
    CloudSyncState: {
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: '1';
      /**
       * Edge Id
       * Format: uuid
       */
      edge_id: string;
      /**
       * Org Id
       * Format: uuid
       */
      org_id: string;
      /**
       * Facility Id
       * Format: uuid
       */
      facility_id: string;
      /**
       * Observed At
       * Format: date-time
       */
      observed_at: string;
      /** Cursors */
      cursors: components['schemas']['CloudStreamCursor'][];
      /**
       * Mode
       * @default SIMULATION
       * @constant
       */
      mode: 'SIMULATION';
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** SyncAck */
    SyncAck: {
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: '1';
      /**
       * Edge Id
       * Format: uuid
       */
      edge_id: string;
      /**
       * Stream
       * @enum {string}
       */
      stream:
        | 'telemetry'
        | 'registry'
        | 'intelligence'
        | 'optimization'
        | 'dispatch'
        | 'finance'
        | 'ai';
      /** Acknowledged Sequence */
      acknowledged_sequence: number;
      /** Accepted */
      accepted: number;
      /** Replayed */
      replayed: number;
      /**
       * Committed At
       * Format: date-time
       */
      committed_at: string;
    };
    /** SyncBatch */
    SyncBatch: {
      /**
       * Schema Version
       * @default 1
       * @constant
       */
      schema_version: '1';
      /**
       * Edge Id
       * Format: uuid
       */
      edge_id: string;
      /**
       * Stream
       * @enum {string}
       */
      stream:
        | 'telemetry'
        | 'registry'
        | 'intelligence'
        | 'optimization'
        | 'dispatch'
        | 'finance'
        | 'ai';
      /** Entries */
      entries: components['schemas']['SyncEntry'][];
    };
    /** SyncEntry */
    SyncEntry: {
      /** Sequence */
      sequence: number;
      /**
       * Event Id
       * Format: uuid
       */
      event_id: string;
      /** Digest */
      digest: string;
      /** Body */
      body: {
        [key: string]: unknown;
      };
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  state_api_v1_sync_state_get: {
    parameters: {
      query?: never;
      header: {
        'X-Edge-ID': string;
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CloudSyncState'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_api_v1_sync_batches_post: {
    parameters: {
      query?: never;
      header: {
        'X-Edge-ID': string;
        Authorization: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SyncBatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SyncAck'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
